"""End-to-end scientific proof pipeline for Keno.

Runs validation, injection campaigns, exports detection calibration, and
writes a reproducible report physicists can audit.

Usage:
    python -m app.prove
    python -m app.prove --skip-campaign          # reuse existing campaign CSVs
    python -m app.prove --quick                  # smaller campaign for CI smoke
    python -m app.prove --train --epochs 30       # retrain before proving
"""

from __future__ import annotations

import argparse
import json
import logging
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

from app.evaluation.baselines import KENO_RESIDUAL_EP_ARTIFACT_TRIM, calibrate_method_thresholds
from app.evaluation.inject import load_cached_segments, sample_noise_only_trial
from app.evaluation.run_campaign import CampaignConfig, run_campaign, run_far_sweep
from app.evaluation.run_coincidence import (
    run_known_event_study,
    run_noise_coincidence_study,
    write_outputs as write_coincidence_outputs,
)
from app.services.subtraction_model import engine

logger = logging.getLogger(__name__)

ROOT = Path(__file__).resolve().parent.parent
EVAL_DIR = ROOT / "data" / "evaluation"
CALIBRATION_PATH = EVAL_DIR / "calibration.json"
REPORT_PATH = ROOT.parent / "docs" / "SCIENTIFIC_VALIDATION.md"


def _run_module(module: str, args: list[str]) -> int:
    cmd = [sys.executable, "-m", module, *args]
    logger.info("Running: %s", " ".join(cmd))
    return subprocess.call(cmd)


def export_calibration(false_alarm_rate: float = 0.01) -> Path:
    """Calibrate excess-power thresholds on cached real noise and write JSON."""
    segments = load_cached_segments()
    rng = __import__("numpy").random.default_rng(42)
    noise_trials = [
        sample_noise_only_trial(segments, 4.0, rng, morphology="unknown") for _ in range(300)
    ]
    thresholds = calibrate_method_thresholds(noise_trials, false_alarm_rate)

    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "false_alarm_rate": false_alarm_rate,
        "noise_trials": len(noise_trials),
        "morphology": "unknown",
        "window_seconds": 4.0,
        "checkpoint_loaded": engine.checkpoint_loaded,
        "excess_power_raw": thresholds["excess_power"],
        "excess_power_residual": thresholds["keno_residual_ep"],
        "mismatched_mf": thresholds["mismatched_mf"],
        "keno_noise_rms_ratio": thresholds["keno"],
        "residual_ep_artifact_trim_fraction": KENO_RESIDUAL_EP_ARTIFACT_TRIM,
        "calibration_note": (
            f"Noise-only GWOSC background at {false_alarm_rate:.1%} target FAR. "
            f"Residual excess-power threshold trims the upper "
            f"{KENO_RESIDUAL_EP_ARTIFACT_TRIM:.0%} of subtraction-glitched trials before calibration."
        ),
    }

    CALIBRATION_PATH.parent.mkdir(parents=True, exist_ok=True)
    CALIBRATION_PATH.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    logger.info("Wrote calibration to %s", CALIBRATION_PATH)
    return CALIBRATION_PATH


def _read_summary(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else "(not run)"


def _parse_summary_metrics(summary_text: str) -> dict[str, str]:
    metrics: dict[str, str] = {}
    current_method = None
    for line in summary_text.splitlines():
        if line.startswith("[") and line.endswith("]"):
            current_method = line.strip("[]")
        elif current_method and "SNR @ 50% efficiency:" in line:
            metrics[f"{current_method}_snr50"] = line.split(":", 1)[1].strip()
    return metrics


def write_report(
    *,
    validate_exit_code: int,
    calibration: dict,
    summary_text: str,
    far_summary_text: str,
    morphology_text: str,
    coincidence_text: str,
) -> Path:
    metrics = _parse_summary_metrics(summary_text)
    passed_validate = validate_exit_code == 0
    checkpoint_note = "loaded" if engine.checkpoint_loaded else "MISSING — random weights"

    report = f"""# Keno Scientific Validation Report

> Auto-generated by `python -m app.prove` on {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}.
> Reproduce: `cd ml-engine && python -m app.prove`

## Hypothesis

Generative denoising isolates unmodeled gravitational-wave bursts better than
template-based classifiers (e.g. AresGW) by subtracting predicted instrumental
noise and searching the residual with template-free statistics:

```
S_clean = S_raw - N_predicted
detection = excess_power(S_clean)
```

AresGW asks: *"Does this 1 s segment contain a BBH merger?"* (binary classification
on a fixed morphology). Keno asks: *"What remains after we remove everything the
model believes is detector noise?"* — the right question for core-collapse supernovae
and other unmodeled transients.

## Model status

| Check | Result |
|-------|--------|
| Checkpoint | {checkpoint_note} |
| Phase 1 validate (`python -m app.training.validate`) | {"PASS" if passed_validate else "FAIL — retrain recommended"} |

## Detection calibration ({calibration.get("false_alarm_rate", 0.01):.1%} target FAR)

Calibrated on {calibration.get("noise_trials", "?")} noise-only windows from cached real GWOSC background.

| Statistic | Threshold |
|-----------|-----------|
| Excess power (raw strain) | {calibration.get("excess_power_raw", "n/a")} |
| Excess power (Keno residual) | {calibration.get("excess_power_residual", "n/a")} |
| Mismatched MF (AresGW-like) | {calibration.get("mismatched_mf", "n/a")} |

Production API: `POST /api/v1/detect` uses these thresholds.

## Injection campaign (unknown morphology)

{summary_text}

## False-alarm rate sweep

{far_summary_text}

## Morphology breakdown

{morphology_text}

## Multi-detector coincidence (Phase 3)

{coincidence_text}

## How to read results

- **keno_residual_ep** — production path: subtract noise, excess power on residual. This is what physicists should trust for blind searches.
- **keno (overlap)** — eval-only recovery metric; requires knowing the injected waveform. High overlap means the burst survived subtraction.
- **mismatched_mf** — proxy for fixed-template methods like AresGW on the wrong morphology. Failure here is expected and is the scientific point.
- **excess_power (raw)** — cWB-style search without subtraction. Keno wins if keno_residual_ep reaches 50% efficiency at lower SNR than raw excess power.

## Key headline metrics (1% FAR)

| Method | SNR @ 50% efficiency |
|--------|---------------------|
| Excess power (raw) | {metrics.get("excess_power_snr50", "see summary")} |
| Keno + residual EP | {metrics.get("keno_residual_ep_snr50", "see summary")} |
| Keno overlap (eval) | {metrics.get("keno_snr50", "see summary")} |
| Mismatched MF | {metrics.get("mismatched_mf_snr50", "see summary")} |

## Reproducibility checklist

1. `python -m app.training.train --epochs 50 --steps-per-epoch 150`
2. `python -m app.training.validate`
3. `python -m app.prove`
4. Inspect `data/evaluation/*.png` and this report.

## What would convince a LIGO collaborator

- [ ] keno_residual_ep beats raw excess_power at 0.1% FAR on unknown morphology
- [ ] Mean normalized recovery error < 0.15 on held-out injections
- [x] Multi-detector coherence (H1 + L1) — see coincidence section above
- [ ] Comparison on real O3 glitch catalogs, not just Gaussian noise
- [ ] Blind follow-up on published cWB event lists

---
*This report is a reproducibility artifact, not a discovery claim.*
"""
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(report, encoding="utf-8")
    logger.info("Wrote report to %s", REPORT_PATH)
    return REPORT_PATH


def prove(args: argparse.Namespace) -> int:
    if args.train:
        train_code = _run_module(
            "app.training.train",
            ["--epochs", str(args.epochs), "--steps-per-epoch", str(args.steps_per_epoch)],
        )
        if train_code != 0:
            logger.error("Training failed with exit code %d", train_code)
            return train_code
        engine.reload_checkpoint()

    validate_code = _run_module("app.training.validate", [])
    calibration_path = export_calibration(args.false_alarm_rate)
    calibration = json.loads(calibration_path.read_text(encoding="utf-8"))

    if not args.skip_campaign:
        config = CampaignConfig(
            snr_min=2.0 if not args.quick else 4.0,
            snr_max=12.0 if not args.quick else 8.0,
            snr_step=2.0 if args.quick else 1.0,
            trials_per_snr=10 if args.quick else 50,
            false_alarm_trials=50 if args.quick else 300,
            false_alarm_rate=args.false_alarm_rate,
            window_seconds=4.0,
            morphology="unknown",
            seeds=(42, 43, 44) if not args.quick else (42,),
            output_dir=EVAL_DIR,
        )
        run_campaign(config, morphology_breakdown=not args.quick)
        if not args.quick:
            run_far_sweep(config, [0.001, 0.01, 0.1])

    coincidence_text = "(not run)"
    if not args.skip_coincidence:
        noise_trials = 10 if args.quick else 50
        known_records, known_results = run_known_event_study(4)
        noise_records = run_noise_coincidence_study(
            noise_trials=noise_trials,
            duration=4,
            seed=42,
        )
        coincidence_path = write_coincidence_outputs(
            known_records=known_records,
            known_results=known_results,
            noise_records=noise_records,
            output_dir=EVAL_DIR,
        )
        coincidence_text = _read_summary(coincidence_path)
    elif (EVAL_DIR / "coincidence_summary.txt").exists():
        coincidence_text = _read_summary(EVAL_DIR / "coincidence_summary.txt")

    report_path = write_report(
        validate_exit_code=validate_code,
        calibration=calibration,
        summary_text=_read_summary(EVAL_DIR / "summary.txt"),
        far_summary_text=_read_summary(EVAL_DIR / "far_sweep_summary.txt"),
        morphology_text=_read_summary(EVAL_DIR / "morphology_breakdown.txt"),
        coincidence_text=coincidence_text,
    )

    print("\n" + "=" * 60)
    print("Keno proof pipeline complete")
    print(f"  Validate:       {'PASS' if validate_code == 0 else 'FAIL'}")
    print(f"  Calibration:    {calibration_path}")
    print(f"  Report:         {report_path}")
    print(f"  Checkpoint:     {'loaded' if engine.checkpoint_loaded else 'MISSING'}")
    print("=" * 60)

    return 0 if validate_code == 0 else 1


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--skip-campaign", action="store_true", help="Reuse existing evaluation outputs")
    parser.add_argument("--skip-coincidence", action="store_true", help="Skip Phase 3 multi-detector study")
    parser.add_argument("--quick", action="store_true", help="Small campaign for smoke testing")
    parser.add_argument("--train", action="store_true", help="Retrain before validation")
    parser.add_argument("--epochs", type=int, default=50)
    parser.add_argument("--steps-per-epoch", type=int, default=150)
    parser.add_argument("--false-alarm-rate", type=float, default=0.01)
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    sys.exit(prove(args))


if __name__ == "__main__":
    main()
